// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: articleCategory.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArticleCategoryService_GetByCategoryId_FullMethodName          = "/articleCategory.ArticleCategoryService/GetByCategoryId"
	ArticleCategoryService_GetCategoryIdByArticleId_FullMethodName = "/articleCategory.ArticleCategoryService/GetCategoryIdByArticleId"
	ArticleCategoryService_SaveArticleCategory_FullMethodName      = "/articleCategory.ArticleCategoryService/SaveArticleCategory"
)

// ArticleCategoryServiceClient is the client API for ArticleCategoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArticleCategoryServiceClient interface {
	GetByCategoryId(ctx context.Context, in *ArticleCategoryIdRequest, opts ...grpc.CallOption) (*ArticleCategoryListResponse, error)
	GetCategoryIdByArticleId(ctx context.Context, in *ArticleCategoryIdRequest, opts ...grpc.CallOption) (*ArticleCategoryIdResponse, error)
	SaveArticleCategory(ctx context.Context, in *ArticleCategoryRequest, opts ...grpc.CallOption) (*ArticleCategoryResponse, error)
}

type articleCategoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleCategoryServiceClient(cc grpc.ClientConnInterface) ArticleCategoryServiceClient {
	return &articleCategoryServiceClient{cc}
}

func (c *articleCategoryServiceClient) GetByCategoryId(ctx context.Context, in *ArticleCategoryIdRequest, opts ...grpc.CallOption) (*ArticleCategoryListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticleCategoryListResponse)
	err := c.cc.Invoke(ctx, ArticleCategoryService_GetByCategoryId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleCategoryServiceClient) GetCategoryIdByArticleId(ctx context.Context, in *ArticleCategoryIdRequest, opts ...grpc.CallOption) (*ArticleCategoryIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticleCategoryIdResponse)
	err := c.cc.Invoke(ctx, ArticleCategoryService_GetCategoryIdByArticleId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleCategoryServiceClient) SaveArticleCategory(ctx context.Context, in *ArticleCategoryRequest, opts ...grpc.CallOption) (*ArticleCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticleCategoryResponse)
	err := c.cc.Invoke(ctx, ArticleCategoryService_SaveArticleCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleCategoryServiceServer is the server API for ArticleCategoryService service.
// All implementations must embed UnimplementedArticleCategoryServiceServer
// for forward compatibility.
type ArticleCategoryServiceServer interface {
	GetByCategoryId(context.Context, *ArticleCategoryIdRequest) (*ArticleCategoryListResponse, error)
	GetCategoryIdByArticleId(context.Context, *ArticleCategoryIdRequest) (*ArticleCategoryIdResponse, error)
	SaveArticleCategory(context.Context, *ArticleCategoryRequest) (*ArticleCategoryResponse, error)
	mustEmbedUnimplementedArticleCategoryServiceServer()
}

// UnimplementedArticleCategoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArticleCategoryServiceServer struct{}

func (UnimplementedArticleCategoryServiceServer) GetByCategoryId(context.Context, *ArticleCategoryIdRequest) (*ArticleCategoryListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByCategoryId not implemented")
}
func (UnimplementedArticleCategoryServiceServer) GetCategoryIdByArticleId(context.Context, *ArticleCategoryIdRequest) (*ArticleCategoryIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategoryIdByArticleId not implemented")
}
func (UnimplementedArticleCategoryServiceServer) SaveArticleCategory(context.Context, *ArticleCategoryRequest) (*ArticleCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveArticleCategory not implemented")
}
func (UnimplementedArticleCategoryServiceServer) mustEmbedUnimplementedArticleCategoryServiceServer() {
}
func (UnimplementedArticleCategoryServiceServer) testEmbeddedByValue() {}

// UnsafeArticleCategoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArticleCategoryServiceServer will
// result in compilation errors.
type UnsafeArticleCategoryServiceServer interface {
	mustEmbedUnimplementedArticleCategoryServiceServer()
}

func RegisterArticleCategoryServiceServer(s grpc.ServiceRegistrar, srv ArticleCategoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedArticleCategoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArticleCategoryService_ServiceDesc, srv)
}

func _ArticleCategoryService_GetByCategoryId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleCategoryIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleCategoryServiceServer).GetByCategoryId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleCategoryService_GetByCategoryId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleCategoryServiceServer).GetByCategoryId(ctx, req.(*ArticleCategoryIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleCategoryService_GetCategoryIdByArticleId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleCategoryIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleCategoryServiceServer).GetCategoryIdByArticleId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleCategoryService_GetCategoryIdByArticleId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleCategoryServiceServer).GetCategoryIdByArticleId(ctx, req.(*ArticleCategoryIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleCategoryService_SaveArticleCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleCategoryServiceServer).SaveArticleCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleCategoryService_SaveArticleCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleCategoryServiceServer).SaveArticleCategory(ctx, req.(*ArticleCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArticleCategoryService_ServiceDesc is the grpc.ServiceDesc for ArticleCategoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArticleCategoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "articleCategory.ArticleCategoryService",
	HandlerType: (*ArticleCategoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByCategoryId",
			Handler:    _ArticleCategoryService_GetByCategoryId_Handler,
		},
		{
			MethodName: "GetCategoryIdByArticleId",
			Handler:    _ArticleCategoryService_GetCategoryIdByArticleId_Handler,
		},
		{
			MethodName: "SaveArticleCategory",
			Handler:    _ArticleCategoryService_SaveArticleCategory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "articleCategory.proto",
}
