// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: articleTag.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArticleTagIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleTagIdRequest) Reset() {
	*x = ArticleTagIdRequest{}
	mi := &file_articleTag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleTagIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleTagIdRequest) ProtoMessage() {}

func (x *ArticleTagIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_articleTag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleTagIdRequest.ProtoReflect.Descriptor instead.
func (*ArticleTagIdRequest) Descriptor() ([]byte, []int) {
	return file_articleTag_proto_rawDescGZIP(), []int{0}
}

func (x *ArticleTagIdRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ArticleTagIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleTagIdsResponse) Reset() {
	*x = ArticleTagIdsResponse{}
	mi := &file_articleTag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleTagIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleTagIdsResponse) ProtoMessage() {}

func (x *ArticleTagIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_articleTag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleTagIdsResponse.ProtoReflect.Descriptor instead.
func (*ArticleTagIdsResponse) Descriptor() ([]byte, []int) {
	return file_articleTag_proto_rawDescGZIP(), []int{1}
}

func (x *ArticleTagIdsResponse) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_articleTag_proto protoreflect.FileDescriptor

var file_articleTag_proto_rawDesc = string([]byte{
	0x0a, 0x10, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x54, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x54, 0x61, 0x67, 0x22, 0x25,
	0x0a, 0x13, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x54, 0x61, 0x67, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x29, 0x0a, 0x15, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x54, 0x61, 0x67, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x03, 0x69, 0x64, 0x73,
	0x32, 0x6f, 0x0a, 0x11, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x54, 0x61, 0x67, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x54, 0x61, 0x67, 0x49,
	0x64, 0x73, 0x42, 0x79, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x2e,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x54, 0x61, 0x67, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x54, 0x61, 0x67, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21,
	0x2e, 0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x54, 0x61, 0x67, 0x2e, 0x41, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x54, 0x61, 0x67, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_articleTag_proto_rawDescOnce sync.Once
	file_articleTag_proto_rawDescData []byte
)

func file_articleTag_proto_rawDescGZIP() []byte {
	file_articleTag_proto_rawDescOnce.Do(func() {
		file_articleTag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_articleTag_proto_rawDesc), len(file_articleTag_proto_rawDesc)))
	})
	return file_articleTag_proto_rawDescData
}

var file_articleTag_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_articleTag_proto_goTypes = []any{
	(*ArticleTagIdRequest)(nil),   // 0: articleTag.ArticleTagIdRequest
	(*ArticleTagIdsResponse)(nil), // 1: articleTag.ArticleTagIdsResponse
}
var file_articleTag_proto_depIdxs = []int32{
	0, // 0: articleTag.ArticleTagService.GetTagIdsByArticleId:input_type -> articleTag.ArticleTagIdRequest
	1, // 1: articleTag.ArticleTagService.GetTagIdsByArticleId:output_type -> articleTag.ArticleTagIdsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_articleTag_proto_init() }
func file_articleTag_proto_init() {
	if File_articleTag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_articleTag_proto_rawDesc), len(file_articleTag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_articleTag_proto_goTypes,
		DependencyIndexes: file_articleTag_proto_depIdxs,
		MessageInfos:      file_articleTag_proto_msgTypes,
	}.Build()
	File_articleTag_proto = out.File
	file_articleTag_proto_goTypes = nil
	file_articleTag_proto_depIdxs = nil
}
