// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: article.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArticleService_GetArticleById_FullMethodName           = "/article.ArticleService/GetArticleById"
	ArticleService_GetArticleDTOById_FullMethodName        = "/article.ArticleService/GetArticleDTOById"
	ArticleService_GetArticleDTOsByKeyWords_FullMethodName = "/article.ArticleService/GetArticleDTOsByKeyWords"
	ArticleService_GetArticleDTOsByUserId_FullMethodName   = "/article.ArticleService/GetArticleDTOsByUserId"
	ArticleService_SaveArticle_FullMethodName              = "/article.ArticleService/SaveArticle"
)

// ArticleServiceClient is the client API for ArticleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArticleServiceClient interface {
	GetArticleById(ctx context.Context, in *ArticleIdRequest, opts ...grpc.CallOption) (*ArticleResponse, error)
	GetArticleDTOById(ctx context.Context, in *ArticleIdRequest, opts ...grpc.CallOption) (*ArticleDTOResponse, error)
	GetArticleDTOsByKeyWords(ctx context.Context, in *ArticleKeywordsRequest, opts ...grpc.CallOption) (*ArticleDTOsResponse, error)
	GetArticleDTOsByUserId(ctx context.Context, in *ArticleIdRequest, opts ...grpc.CallOption) (*ArticleDTOsResponse, error)
	SaveArticle(ctx context.Context, in *ArticleRequest, opts ...grpc.CallOption) (*SaveArticleResponse, error)
}

type articleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleServiceClient(cc grpc.ClientConnInterface) ArticleServiceClient {
	return &articleServiceClient{cc}
}

func (c *articleServiceClient) GetArticleById(ctx context.Context, in *ArticleIdRequest, opts ...grpc.CallOption) (*ArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticleResponse)
	err := c.cc.Invoke(ctx, ArticleService_GetArticleById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) GetArticleDTOById(ctx context.Context, in *ArticleIdRequest, opts ...grpc.CallOption) (*ArticleDTOResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticleDTOResponse)
	err := c.cc.Invoke(ctx, ArticleService_GetArticleDTOById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) GetArticleDTOsByKeyWords(ctx context.Context, in *ArticleKeywordsRequest, opts ...grpc.CallOption) (*ArticleDTOsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticleDTOsResponse)
	err := c.cc.Invoke(ctx, ArticleService_GetArticleDTOsByKeyWords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) GetArticleDTOsByUserId(ctx context.Context, in *ArticleIdRequest, opts ...grpc.CallOption) (*ArticleDTOsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArticleDTOsResponse)
	err := c.cc.Invoke(ctx, ArticleService_GetArticleDTOsByUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) SaveArticle(ctx context.Context, in *ArticleRequest, opts ...grpc.CallOption) (*SaveArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveArticleResponse)
	err := c.cc.Invoke(ctx, ArticleService_SaveArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleServiceServer is the server API for ArticleService service.
// All implementations must embed UnimplementedArticleServiceServer
// for forward compatibility.
type ArticleServiceServer interface {
	GetArticleById(context.Context, *ArticleIdRequest) (*ArticleResponse, error)
	GetArticleDTOById(context.Context, *ArticleIdRequest) (*ArticleDTOResponse, error)
	GetArticleDTOsByKeyWords(context.Context, *ArticleKeywordsRequest) (*ArticleDTOsResponse, error)
	GetArticleDTOsByUserId(context.Context, *ArticleIdRequest) (*ArticleDTOsResponse, error)
	SaveArticle(context.Context, *ArticleRequest) (*SaveArticleResponse, error)
	mustEmbedUnimplementedArticleServiceServer()
}

// UnimplementedArticleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArticleServiceServer struct{}

func (UnimplementedArticleServiceServer) GetArticleById(context.Context, *ArticleIdRequest) (*ArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticleById not implemented")
}
func (UnimplementedArticleServiceServer) GetArticleDTOById(context.Context, *ArticleIdRequest) (*ArticleDTOResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticleDTOById not implemented")
}
func (UnimplementedArticleServiceServer) GetArticleDTOsByKeyWords(context.Context, *ArticleKeywordsRequest) (*ArticleDTOsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticleDTOsByKeyWords not implemented")
}
func (UnimplementedArticleServiceServer) GetArticleDTOsByUserId(context.Context, *ArticleIdRequest) (*ArticleDTOsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticleDTOsByUserId not implemented")
}
func (UnimplementedArticleServiceServer) SaveArticle(context.Context, *ArticleRequest) (*SaveArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveArticle not implemented")
}
func (UnimplementedArticleServiceServer) mustEmbedUnimplementedArticleServiceServer() {}
func (UnimplementedArticleServiceServer) testEmbeddedByValue()                        {}

// UnsafeArticleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArticleServiceServer will
// result in compilation errors.
type UnsafeArticleServiceServer interface {
	mustEmbedUnimplementedArticleServiceServer()
}

func RegisterArticleServiceServer(s grpc.ServiceRegistrar, srv ArticleServiceServer) {
	// If the following call pancis, it indicates UnimplementedArticleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArticleService_ServiceDesc, srv)
}

func _ArticleService_GetArticleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).GetArticleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleService_GetArticleById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).GetArticleById(ctx, req.(*ArticleIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_GetArticleDTOById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).GetArticleDTOById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleService_GetArticleDTOById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).GetArticleDTOById(ctx, req.(*ArticleIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_GetArticleDTOsByKeyWords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleKeywordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).GetArticleDTOsByKeyWords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleService_GetArticleDTOsByKeyWords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).GetArticleDTOsByKeyWords(ctx, req.(*ArticleKeywordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_GetArticleDTOsByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).GetArticleDTOsByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleService_GetArticleDTOsByUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).GetArticleDTOsByUserId(ctx, req.(*ArticleIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_SaveArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).SaveArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleService_SaveArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).SaveArticle(ctx, req.(*ArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArticleService_ServiceDesc is the grpc.ServiceDesc for ArticleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArticleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "article.ArticleService",
	HandlerType: (*ArticleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArticleById",
			Handler:    _ArticleService_GetArticleById_Handler,
		},
		{
			MethodName: "GetArticleDTOById",
			Handler:    _ArticleService_GetArticleDTOById_Handler,
		},
		{
			MethodName: "GetArticleDTOsByKeyWords",
			Handler:    _ArticleService_GetArticleDTOsByKeyWords_Handler,
		},
		{
			MethodName: "GetArticleDTOsByUserId",
			Handler:    _ArticleService_GetArticleDTOsByUserId_Handler,
		},
		{
			MethodName: "SaveArticle",
			Handler:    _ArticleService_SaveArticle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "article.proto",
}
