// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: userFollow.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserFollowService_GetUserFollowerIds_FullMethodName  = "/userFollow.UserFollowService/GetUserFollowerIds"
	UserFollowService_GetUserFollowingIds_FullMethodName = "/userFollow.UserFollowService/GetUserFollowingIds"
	UserFollowService_GetIsFollow_FullMethodName         = "/userFollow.UserFollowService/GetIsFollow"
	UserFollowService_SetIsFollow_FullMethodName         = "/userFollow.UserFollowService/SetIsFollow"
)

// UserFollowServiceClient is the client API for UserFollowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserFollowServiceClient interface {
	GetUserFollowerIds(ctx context.Context, in *UserFollowIdRequest, opts ...grpc.CallOption) (*UserFollowIdResponse, error)
	GetUserFollowingIds(ctx context.Context, in *UserFollowIdRequest, opts ...grpc.CallOption) (*UserFollowIdResponse, error)
	GetIsFollow(ctx context.Context, in *IsFollowedRequest, opts ...grpc.CallOption) (*IsFollowResponse, error)
	SetIsFollow(ctx context.Context, in *IsFollowedRequest, opts ...grpc.CallOption) (*IsFollowResponse, error)
}

type userFollowServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserFollowServiceClient(cc grpc.ClientConnInterface) UserFollowServiceClient {
	return &userFollowServiceClient{cc}
}

func (c *userFollowServiceClient) GetUserFollowerIds(ctx context.Context, in *UserFollowIdRequest, opts ...grpc.CallOption) (*UserFollowIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserFollowIdResponse)
	err := c.cc.Invoke(ctx, UserFollowService_GetUserFollowerIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userFollowServiceClient) GetUserFollowingIds(ctx context.Context, in *UserFollowIdRequest, opts ...grpc.CallOption) (*UserFollowIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserFollowIdResponse)
	err := c.cc.Invoke(ctx, UserFollowService_GetUserFollowingIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userFollowServiceClient) GetIsFollow(ctx context.Context, in *IsFollowedRequest, opts ...grpc.CallOption) (*IsFollowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsFollowResponse)
	err := c.cc.Invoke(ctx, UserFollowService_GetIsFollow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userFollowServiceClient) SetIsFollow(ctx context.Context, in *IsFollowedRequest, opts ...grpc.CallOption) (*IsFollowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsFollowResponse)
	err := c.cc.Invoke(ctx, UserFollowService_SetIsFollow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserFollowServiceServer is the server API for UserFollowService service.
// All implementations must embed UnimplementedUserFollowServiceServer
// for forward compatibility.
type UserFollowServiceServer interface {
	GetUserFollowerIds(context.Context, *UserFollowIdRequest) (*UserFollowIdResponse, error)
	GetUserFollowingIds(context.Context, *UserFollowIdRequest) (*UserFollowIdResponse, error)
	GetIsFollow(context.Context, *IsFollowedRequest) (*IsFollowResponse, error)
	SetIsFollow(context.Context, *IsFollowedRequest) (*IsFollowResponse, error)
	mustEmbedUnimplementedUserFollowServiceServer()
}

// UnimplementedUserFollowServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserFollowServiceServer struct{}

func (UnimplementedUserFollowServiceServer) GetUserFollowerIds(context.Context, *UserFollowIdRequest) (*UserFollowIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserFollowerIds not implemented")
}
func (UnimplementedUserFollowServiceServer) GetUserFollowingIds(context.Context, *UserFollowIdRequest) (*UserFollowIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserFollowingIds not implemented")
}
func (UnimplementedUserFollowServiceServer) GetIsFollow(context.Context, *IsFollowedRequest) (*IsFollowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIsFollow not implemented")
}
func (UnimplementedUserFollowServiceServer) SetIsFollow(context.Context, *IsFollowedRequest) (*IsFollowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetIsFollow not implemented")
}
func (UnimplementedUserFollowServiceServer) mustEmbedUnimplementedUserFollowServiceServer() {}
func (UnimplementedUserFollowServiceServer) testEmbeddedByValue()                           {}

// UnsafeUserFollowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserFollowServiceServer will
// result in compilation errors.
type UnsafeUserFollowServiceServer interface {
	mustEmbedUnimplementedUserFollowServiceServer()
}

func RegisterUserFollowServiceServer(s grpc.ServiceRegistrar, srv UserFollowServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserFollowServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserFollowService_ServiceDesc, srv)
}

func _UserFollowService_GetUserFollowerIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFollowIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserFollowServiceServer).GetUserFollowerIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserFollowService_GetUserFollowerIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserFollowServiceServer).GetUserFollowerIds(ctx, req.(*UserFollowIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserFollowService_GetUserFollowingIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFollowIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserFollowServiceServer).GetUserFollowingIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserFollowService_GetUserFollowingIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserFollowServiceServer).GetUserFollowingIds(ctx, req.(*UserFollowIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserFollowService_GetIsFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsFollowedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserFollowServiceServer).GetIsFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserFollowService_GetIsFollow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserFollowServiceServer).GetIsFollow(ctx, req.(*IsFollowedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserFollowService_SetIsFollow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsFollowedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserFollowServiceServer).SetIsFollow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserFollowService_SetIsFollow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserFollowServiceServer).SetIsFollow(ctx, req.(*IsFollowedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserFollowService_ServiceDesc is the grpc.ServiceDesc for UserFollowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserFollowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "userFollow.UserFollowService",
	HandlerType: (*UserFollowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserFollowerIds",
			Handler:    _UserFollowService_GetUserFollowerIds_Handler,
		},
		{
			MethodName: "GetUserFollowingIds",
			Handler:    _UserFollowService_GetUserFollowingIds_Handler,
		},
		{
			MethodName: "GetIsFollow",
			Handler:    _UserFollowService_GetIsFollow_Handler,
		},
		{
			MethodName: "SetIsFollow",
			Handler:    _UserFollowService_SetIsFollow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "userFollow.proto",
}
