basePath: /
host: localhost:8080
info:
  contact: {}
  description: 这是一个博客项目
  title: blog
  version: "1.0"
paths:
  /article:
    get:
      parameters:
      - description: 用户 ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: 通过id过去文章
swagger: "2.0"
